package router

import (
	"net/http"

	"github.com/example/ems/internal/app"
	authmodel "github.com/example/ems/internal/auth/model"
	"github.com/example/ems/internal/middleware"
	"github.com/gin-gonic/gin"
	swaggerfiles "github.com/swaggo/files"
	ginswagger "github.com/swaggo/gin-swagger"

	// Generated by `swag init`; provides the OpenAPI spec served at /swagger.
	_ "github.com/example/ems/docs"
)

// Setup builds the Gin engine with global middleware and all route groups.
func Setup(c *app.Container) *gin.Engine {
	if c.Config.IsProduction() {
		gin.SetMode(gin.ReleaseMode)
	}

	r := gin.New()
	r.Use(
		middleware.RequestID(),
		middleware.Logger(c.Logger),
		middleware.Recovery(c.Logger),
		middleware.CORS(),
	)

	// Health & docs (unauthenticated).
	r.GET("/health", func(ctx *gin.Context) {
		ctx.JSON(http.StatusOK, gin.H{"status": "ok"})
	})
	r.GET("/swagger/*any", ginswagger.WrapHandler(swaggerfiles.Handler))

	v1 := r.Group("/api/v1")

	// Auth (public).
	auth := v1.Group("/auth")
	{
		auth.POST("/register", c.AuthHandler.Register)
		auth.POST("/login", c.AuthHandler.Login)
		auth.POST("/refresh", c.AuthHandler.Refresh)
	}

	// Authenticated routes.
	authd := v1.Group("")
	authd.Use(middleware.Authenticate(c.JWT))
	{
		// Management-only access (company-wide views).
		manageRoles := middleware.RequireRoles(string(authmodel.RoleAdmin), string(authmodel.RoleHR))

		// Self-service: any authenticated role fetches only their own record.
		// Kept as a top-level path (not /employees/me) to avoid colliding with
		// the /employees/:id wildcard in Gin's router.
		authd.GET("/me", c.EmployeeHandler.Me)

		// Company-wide dashboard stats are management-only.
		authd.GET("/dashboard", manageRoles, c.DashboardHandler.Stats)

		emp := authd.Group("/employees")
		{
			// Reads: Admin and HR only. Employees use GET /me for their own data.
			emp.GET("", manageRoles, c.EmployeeHandler.List)
			emp.GET("/:id", manageRoles, c.EmployeeHandler.Get)

			// Writes: Admin and HR only.
			writeRoles := middleware.RequireRoles(string(authmodel.RoleAdmin), string(authmodel.RoleHR))
			emp.POST("", writeRoles, c.EmployeeHandler.Create)
			emp.PUT("/:id", writeRoles, c.EmployeeHandler.Update)
			emp.DELETE("/:id", middleware.RequireRoles(string(authmodel.RoleAdmin)), c.EmployeeHandler.Delete)
		}
	}

	return r
}
